services:
  mongo:
    image: mongo:5.0.2
    ports:
      - "27017:27017"
    volumes:
      - ~/mangilaspringbootrestfulservicemongodb:/data/db
  redis:
    image: redis:6.2.0-alpine
    ports:
      - "6379:6379"
  api:
    image: apiimage
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    links:
      - mongo
      - redis
    depends_on:
      - mongo
      - redis